// AUTO-GEGENEREERD — niet handmatig bewerken. Run: pnpm generate-schemas
// Gegenereerd op: 2026-05-15T09:47:54.305Z

export type EndpointSchema = {
  fields: Record<string, string>;
  numeric_fields: string[];
};

export const ENDPOINT_SCHEMAS: Record<string, EndpointSchema> = {
  "huishoudelijkafval/container": {
    fields: {
    "id": "string",
    "idNummer": "string",
    "serienummer": "string",
    "clusterId": "unknown",
    "eigenaarId": "string",
    "eigenaarNaam": "string",
    "status": "integer",
    "fractieCode": "string",
    "fractieOmschrijving": "string",
    "datumCreatie": "date",
    "datumPlaatsing": "date",
    "datumOperationeel": "date",
    "datumAflopenGarantie": "date",
    "datumOplevering": "date",
    "wijzigingsdatumDp": "date",
    "verwijderdDp": "boolean",
    "geadopteerdInd": "boolean",
    "locatieId": "string",
    "typeId": "string",
    "bagHoofdadresVerblijfsobjectId": "unknown",
    "gbdBuurtId": "string",
    "bagOpenbareruimteId": "unknown",
    "bagNummeraanduidingId": "unknown",
    "containerRalKleurNaam": "unknown",
    "containerRalKleurCode": "unknown",
    "containerRalKleurHexcode": "unknown",
    "containerChipNummber": "unknown",
    "containerUnitCardLezerId": "unknown",
    "containerKleur": "string",
    "containerMark": "unknown",
    "containerDatumVervanging": "unknown",
    "containerDatumWijziging": "date",
    "containerEndOfLife": "unknown",
    "containerEigenaarschap": "string",
    "containerEigenaarschapOpmerking": "string",
    "containerOpmerking": "unknown"
    },
    numeric_fields: ["status"],
  },
  "afvalwijzer/afvalwijzer": {
    fields: {
    "id": "string",
    "straatnaam": "string",
    "huisnummer": "integer",
    "huisletter": "unknown",
    "huisnummertoevoeging": "string",
    "postcode": "string",
    "woonplaatsnaam": "string",
    "statusAdres": "string",
    "gebruiksdoelWoonfunctie": "boolean",
    "afvalwijzerInstructie": "unknown",
    "afvalwijzerBasisroutetypeId": "string",
    "afvalwijzerRoutenaam": "string",
    "afvalwijzerPerXWeken": "string",
    "afvalwijzerBuitenzettenVanafTot": "string",
    "afvalwijzerBuitenzettenVanaf": "string",
    "afvalwijzerBuitenzettenTot": "string",
    "afvalwijzerAfvalkalenderOpmerking": "string",
    "afvalwijzerAfvalkalenderFrequentie": "string",
    "afvalwijzerFractieNaam": "string",
    "afvalwijzerFractieCode": "string",
    "afvalwijzerFractieVolgnummer": "integer",
    "afvalwijzerRoutetypeNaam": "string",
    "afvalwijzerOphaaldagen": "string",
    "afvalwijzerOphaaldagenArray": "array",
    "afvalwijzerAfvalkalenderMelding": "unknown",
    "afvalwijzerAfvalkalenderVan": "unknown",
    "afvalwijzerAfvalkalenderTot": "unknown",
    "afvalwijzerBasisroutetype": "string",
    "afvalwijzerBasisroutetypeOmschrijving": "string",
    "afvalwijzerBasisroutetypeCode": "string",
    "afvalwijzerInstructie2": "string",
    "afvalwijzerOphaaldagen2": "string",
    "afvalwijzerOphaaldagen2Array": "array",
    "afvalwijzerWaar": "string",
    "afvalwijzerBuitenzetten": "string",
    "afvalwijzerButtontekst": "string",
    "afvalwijzerUrl": "string",
    "bagNummeraanduidingId": "string",
    "gbdBuurtId": "string",
    "gbdBuurtCode": "string",
    "afvalwijzerInzamelgebiedNaam": "string",
    "afvalwijzerInzamelgebiedCode": "string"
    },
    numeric_fields: ["huisnummer", "afvalwijzerFractieVolgnummer"],
  },
  "recyclepunten/wegingen": {
    fields: {
    "id": "integer",
    "weegbon": "string",
    "datumWeging": "date",
    "tijdIn": "string",
    "tijdUit": "string",
    "inweging": "integer",
    "uitweging": "integer",
    "nettoGewicht": "integer",
    "locatieCode": "string",
    "locatieNaam": "string",
    "tariefgroepCode": "string",
    "tariefgroepNaam": "string",
    "postcodeBezoeker": "string",
    "afvalstroomNummer": "string"
    },
    numeric_fields: ["id", "inweging", "uitweging", "nettoGewicht"],
  },
  "bag/verblijfsobjecten": {
    fields: {
    "identificatie": "string",
    "volgnummer": "integer",
    "plusvolgnummer": "integer",
    "registratiedatum": "date",
    "cbsNummer": "unknown",
    "indicatieWoningvoorraad": "unknown",
    "financieringscodeCode": "unknown",
    "financieringscodeOmschrijving": "unknown",
    "geconstateerd": "boolean",
    "heeftHoofdadresId": "string",
    "oppervlakte": "integer",
    "statusCode": "unknown",
    "statusOmschrijving": "string",
    "beginGeldigheid": "date",
    "eindGeldigheid": "unknown",
    "documentdatum": "date",
    "documentnummer": "string",
    "gebruiksdoelWoonfunctieCode": "unknown",
    "gebruiksdoelWoonfunctieOmschrijving": "unknown",
    "gebruiksdoelGezondheidszorgfunctieCode": "unknown",
    "gebruiksdoelGezondheidszorgfunctieOmschrijving": "unknown",
    "aantalEenhedenComplex": "unknown",
    "verdiepingToegang": "integer",
    "aantalBouwlagen": "integer",
    "hoogsteBouwlaag": "unknown",
    "laagsteBouwlaag": "unknown",
    "aantalKamers": "integer",
    "eigendomsverhoudingCode": "unknown",
    "eigendomsverhoudingOmschrijving": "unknown",
    "feitelijkGebruikCode": "unknown",
    "feitelijkGebruikOmschrijving": "unknown",
    "redenopvoerCode": "unknown",
    "redenopvoerOmschrijving": "unknown",
    "redenafvoerCode": "unknown",
    "redenafvoerOmschrijving": "unknown",
    "ligtInBuurtId": "string",
    "heeftDossierId": "unknown",
    "bagprocesCode": "unknown",
    "bagprocesOmschrijving": "string",
    "datumActueelTot": "unknown",
    "gebruiksdoel": "array",
    "toegang": "array"
    },
    numeric_fields: ["volgnummer", "plusvolgnummer", "oppervlakte", "verdiepingToegang", "aantalBouwlagen", "aantalKamers"],
  },
  "bag/panden": {
    fields: {
    "identificatie": "string",
    "volgnummer": "integer",
    "plusvolgnummer": "integer",
    "registratiedatum": "date",
    "geconstateerd": "boolean",
    "oorspronkelijkBouwjaar": "integer",
    "statusCode": "unknown",
    "statusOmschrijving": "string",
    "beginGeldigheid": "date",
    "eindGeldigheid": "unknown",
    "documentdatum": "date",
    "documentnummer": "string",
    "naam": "unknown",
    "liggingCode": "unknown",
    "liggingOmschrijving": "string",
    "typeWoonobject": "string",
    "ligtInBouwblokId": "string",
    "ligtInBuurtId": "string",
    "aantalBouwlagen": "integer",
    "hoogsteBouwlaag": "integer",
    "laagsteBouwlaag": "integer",
    "heeftDossierId": "unknown",
    "bagprocesCode": "unknown",
    "bagprocesOmschrijving": "string",
    "datumActueelTot": "unknown"
    },
    numeric_fields: ["volgnummer", "plusvolgnummer", "oorspronkelijkBouwjaar", "aantalBouwlagen", "hoogsteBouwlaag", "laagsteBouwlaag"],
  },
  "bag/nummeraanduidingen": {
    fields: {
    "identificatie": "string",
    "volgnummer": "integer",
    "plusvolgnummer": "integer",
    "registratiedatum": "date",
    "huisnummer": "integer",
    "geconstateerd": "boolean",
    "huisletter": "unknown",
    "huisnummertoevoeging": "string",
    "postcode": "string",
    "ligtInWoonplaatsId": "string",
    "beginGeldigheid": "date",
    "eindGeldigheid": "unknown",
    "ligtAanOpenbareruimteId": "string",
    "typeAdresseerbaarObjectCode": "integer",
    "typeAdresseerbaarObjectOmschrijving": "string",
    "documentdatum": "date",
    "documentnummer": "string",
    "statusCode": "unknown",
    "statusOmschrijving": "string",
    "typeAdres": "string",
    "adresseertVerblijfsobjectId": "string",
    "adresseertLigplaatsId": "unknown",
    "adresseertStandplaatsId": "unknown",
    "heeftDossierId": "unknown",
    "bagprocesCode": "unknown",
    "bagprocesOmschrijving": "unknown",
    "datumActueelTot": "unknown"
    },
    numeric_fields: ["volgnummer", "plusvolgnummer", "huisnummer", "typeAdresseerbaarObjectCode"],
  },
  "bag/openbareruimtes": {
    fields: {
    "identificatie": "string",
    "volgnummer": "integer",
    "plusvolgnummer": "integer",
    "registratiedatum": "date",
    "straatcode": "unknown",
    "straatnaamPtt": "unknown",
    "statusCode": "unknown",
    "statusOmschrijving": "string",
    "beginGeldigheid": "date",
    "eindGeldigheid": "unknown",
    "geconstateerd": "boolean",
    "typeCode": "unknown",
    "typeOmschrijving": "string",
    "documentdatum": "date",
    "documentnummer": "string",
    "naam": "string",
    "naamNen": "string",
    "ligtInWoonplaatsId": "string",
    "beschrijvingNaam": "string",
    "heeftDossierId": "unknown",
    "bagprocesCode": "unknown",
    "bagprocesOmschrijving": "unknown",
    "datumActueelTot": "unknown",
    "opgemaakteNaam": "string"
    },
    numeric_fields: ["volgnummer", "plusvolgnummer"],
  },
  "bag/woonplaatsen": {
    fields: {
    "identificatie": "string",
    "volgnummer": "integer",
    "plusvolgnummer": "integer",
    "registratiedatum": "date",
    "woonplaatsPtt": "unknown",
    "naam": "string",
    "geconstateerd": "string",
    "beginGeldigheid": "date",
    "eindGeldigheid": "unknown",
    "documentdatum": "date",
    "documentnummer": "string",
    "statusCode": "unknown",
    "statusOmschrijving": "string",
    "ligtInGemeenteId": "string",
    "heeftDossierId": "unknown",
    "bagprocesCode": "unknown",
    "bagprocesOmschrijving": "string",
    "datumActueelTot": "unknown"
    },
    numeric_fields: ["volgnummer", "plusvolgnummer"],
  },
  "bag/standplaatsen": {
    fields: {
    "identificatie": "string",
    "volgnummer": "integer",
    "plusvolgnummer": "integer",
    "registratiedatum": "date",
    "geconstateerd": "boolean",
    "statusCode": "unknown",
    "statusOmschrijving": "string",
    "heeftHoofdadresId": "string",
    "beginGeldigheid": "date",
    "eindGeldigheid": "unknown",
    "documentdatum": "date",
    "documentnummer": "string",
    "ligtInBuurtId": "string",
    "heeftDossierId": "unknown",
    "bagprocesCode": "unknown",
    "bagprocesOmschrijving": "unknown",
    "datumActueelTot": "unknown",
    "gebruiksdoel": "array"
    },
    numeric_fields: ["volgnummer", "plusvolgnummer"],
  },
  "bag/ligplaatsen": {
    fields: {
    "identificatie": "string",
    "volgnummer": "integer",
    "plusvolgnummer": "integer",
    "registratiedatum": "date",
    "geconstateerd": "boolean",
    "statusCode": "unknown",
    "statusOmschrijving": "string",
    "heeftHoofdadresId": "string",
    "beginGeldigheid": "date",
    "eindGeldigheid": "unknown",
    "documentdatum": "date",
    "documentnummer": "string",
    "ligtInBuurtId": "string",
    "heeftDossierId": "unknown",
    "bagprocesCode": "unknown",
    "bagprocesOmschrijving": "unknown",
    "datumActueelTot": "unknown",
    "gebruiksdoel": "array"
    },
    numeric_fields: ["volgnummer", "plusvolgnummer"],
  },
  "aardgasvrijezones/buurt": {
    fields: {
    "id": "integer",
    "buurtCode": "string",
    "buurtNaam": "string",
    "toelichting": "string",
    "aandeelKookgas": "string"
    },
    numeric_fields: ["id"],
  },
  "duurzaamheid/energielabel": {
    fields: {
    "id": "string",
    "registratiedatum": "date",
    "opnamedatum": "date",
    "metingGeldigTot": "date",
    "certificaathouder": "string",
    "opnametype": "unknown",
    "status": "unknown",
    "berekeningstype": "string",
    "isOpBasisVanReferentieGebouw": "unknown",
    "gebouwklasse": "string",
    "gebouwtype": "string",
    "gebouwsubtype": "string",
    "sbicode": "unknown",
    "postcode": "string",
    "huisnummer": "integer",
    "huisletter": "string",
    "huisnummertoevoeging": "string",
    "detailaanduiding": "unknown",
    "bagVerblijfsobjectId": "string",
    "bagLigplaatsId": "unknown",
    "bagStandplaatsId": "unknown",
    "bagPandIds": "unknown",
    "projectnaam": "unknown",
    "projectobject": "unknown",
    "bouwjaar": "integer",
    "gebruiksoppervlakteThermischeZone": "unknown",
    "compactheid": "unknown",
    "energieklasse": "string",
    "energieindex": "string",
    "energieindexMetEmgForfaitair": "string",
    "eisEnergiebehoefte": "unknown",
    "primaireFossieleEnergie": "unknown",
    "primaireFossieleEnergieEmgForfaitair": "unknown",
    "aandeelHernieuwbareEnergie": "unknown",
    "aandeelHernieuwbareEnergieEmgForfaitair": "unknown",
    "temperatuuroverschrijding": "unknown",
    "warmtebehoefte": "unknown",
    "energiebehoefte": "unknown",
    "eisPrimaireFossieleEnergie": "unknown",
    "eisAandeelHernieuwbareEnergie": "unknown",
    "eisTemperatuuroverschrijding": "unknown",
    "berekendeCo2Emissie": "string",
    "berekendeEnergieverbruik": "string"
    },
    numeric_fields: ["huisnummer", "bouwjaar"],
  },
  "energieverbruik_mra/gas_en_elektriciteit_kwartaal": {
    fields: {
    "id": "integer",
    "peildatum": "date",
    "jaar": "integer",
    "jaarKwartaal": "string",
    "product": "string",
    "klantsegment": "string",
    "gemeente": "string",
    "wijkCode": "string",
    "wijkNaam": "string",
    "buurtCode": "string",
    "buurtNaam": "string",
    "standaardjaarLevering": "integer",
    "standaardjaarTeruglevering": "integer",
    "aantalAansluitingen": "integer",
    "netbeheerder": "string"
    },
    numeric_fields: ["id", "jaar", "standaardjaarLevering", "standaardjaarTeruglevering", "aantalAansluitingen"],
  },
  "monumenten/monumenten": {
    fields: {
    "identificatie": "string",
    "monumentnummer": "integer",
    "adressering": "string",
    "naam": "unknown",
    "type": "string",
    "status": "string",
    "datumAanwijzing": "date",
    "datumAfvoeren": "unknown",
    "inOnderzoek": "string",
    "architectOntwerp": "string",
    "opdrachtgeverBouw": "string",
    "jaarBeginVan": "string",
    "jaarBeginTot": "string",
    "oorspronkelijkeFunctie": "string",
    "redengevendeOmschrijvingPubliek": "string",
    "beschrijvingPubliek": "unknown",
    "ligtInMonumentenComplexId": "unknown",
    "datumActueelTot": "unknown",
    "contour": "unknown"
    },
    numeric_fields: ["monumentnummer"],
  },
  "beschermdestadsdorpsgezichten/beschermdestadsdorpsgezichten": {
    fields: {
    "id": "integer",
    "naam": "string",
    "aangewezenDoor": "string",
    "status": "string",
    "aanwijzingsdatum": "date",
    "intrekkingsdatum": "unknown",
    "toelichting": "string",
    "besluitAanwijzing": "string",
    "extraInformatie": "string"
    },
    numeric_fields: ["id"],
  },
  "amsterdam_canon/canon_amsterdam_2025": {
    fields: {
    "id": "integer",
    "jaartal": "string",
    "titel": "string",
    "locatieBeschrijving": "string",
    "thema": "string",
    "urlStadsarchief": "string",
    "stadsdeelNaam": "string",
    "geometrieWgs84": "string"
    },
    numeric_fields: ["id"],
  },
  "bomen/stamgegevens": {
    fields: {
    "id": "integer",
    "gbdBuurtId": "string",
    "typeBeheerderPlus": "string",
    "boomhoogteklasseActueel": "string",
    "typeEigenaarPlus": "string",
    "jaarVanAanleg": "integer",
    "soortnaam": "string",
    "stamdiameterklasse": "string",
    "standplaats": "string",
    "standplaatsGedetailleerd": "string",
    "typeObject": "string",
    "typeSoortnaam": "string",
    "groeiplaatsBoomId": "unknown",
    "beschermingsstatusGedetailleerd": "unknown",
    "beschermingsstatus": "unknown",
    "geldigVanaf": "date",
    "mutatieDatum": "date",
    "soortnaamKort": "string",
    "soortnaamTop": "string"
    },
    numeric_fields: ["id", "jaarVanAanleg"],
  },
  "ecologie/kerngebieden": {
    fields: {
    "id": "integer",
    "categorieKerngebied": "string",
    "gidssoort": "string",
    "objectnaam": "string",
    "objectnummer": "unknown",
    "objecttype": "unknown",
    "omtrekGis": "number",
    "oppervlakteGis": "number",
    "stadsdeelNaam": "string",
    "waterschapNaam": "unknown",
    "wijkNaam": "string",
    "mutatieDatum": "date",
    "woonplaatsNaam": "string"
    },
    numeric_fields: ["id", "omtrekGis", "oppervlakteGis"],
  },
  "ziekte_plagen_exoten_groen/eikenprocessierups": {
    fields: {
    "id": "string",
    "boomid": "string",
    "gbdBuurtId": "string",
    "sigNrmelding": "string",
    "datumMelding": "date",
    "datumBestrijding": "unknown",
    "urgentie": "string",
    "status": "string",
    "urgentieStatusKaartlaag": "string",
    "soortnaam": "string",
    "boomhoogteklasseActueel": "string",
    "ranking": "integer"
    },
    numeric_fields: ["ranking"],
  },
  "functionele_gebieden/groen": {
    fields: {
    "id": "integer",
    "functie": "string",
    "naam": "string",
    "bron": "string",
    "bronId": "string"
    },
    numeric_fields: ["id"],
  },
  "meldingen/meldingen": {
    fields: {
    "id": "string",
    "hoofdcategorie": "string",
    "subcategorie": "string",
    "thema": "string",
    "datumMelding": "date",
    "tijdstipMelding": "string",
    "datumOverlast": "date",
    "tijdstipOverlast": "string",
    "externeStatus": "string",
    "meldingType": "string",
    "meldingSoort": "string",
    "gbdBuurtCode": "string",
    "gbdBuurtNaam": "string",
    "gbdBuurtId": "string",
    "gbdWijkCode": "string",
    "gbdWijkNaam": "string",
    "gbdWijkId": "string",
    "gbdGgwgebiedCode": "string",
    "gbdGgwgebiedNaam": "string",
    "gbdGgwgebiedId": "string",
    "gbdStadsdeelCode": "string",
    "gbdStadsdeelNaam": "string",
    "gbdStadsdeelId": "string",
    "bagWoonplaatsNaam": "string",
    "bagWoonplaatsId": "string",
    "bron": "string",
    "laatstGezienBron": "date",
    "latitudeVisualisatie": "number",
    "longitudeVisualisatie": "number"
    },
    numeric_fields: ["latitudeVisualisatie", "longitudeVisualisatie"],
  },
  "bgt/wegdelen": {
    fields: {
    "bgtFunctie": "string",
    "plusFunctie": "string",
    "bgtFysiekVoorkomen": "string",
    "plusFysiekVoorkomen": "string",
    "opTalud": "string",
    "kruinlijn": "unknown",
    "objectBegintijd": "date",
    "objectEindtijd": "unknown",
    "identificatie": "string",
    "volgnummer": "integer",
    "tijdstipRegistratie": "date",
    "eindRegistratie": "unknown",
    "lvPublicatie": "date",
    "bronhouder": "string",
    "inOnderzoek": "string",
    "relatieveHoogteligging": "integer",
    "bgtStatus": "string",
    "plusStatus": "unknown",
    "datumActueelTot": "unknown"
    },
    numeric_fields: ["volgnummer", "relatieveHoogteligging"],
  },
  "nap/peilmerken": {
    fields: {
    "identificatie": "string",
    "hoogteTovNap": "number",
    "jaar": "integer",
    "merkCode": "string",
    "merkOmschrijving": "string",
    "omschrijving": "string",
    "windrichting": "string",
    "xCoordinaatMuurvlak": "integer",
    "yCoordinaatMuurvlak": "integer",
    "rwsNummer": "string",
    "statusCode": "integer",
    "statusOmschrijving": "string",
    "vervaldatum": "date",
    "ligtInBouwblokId": "unknown",
    "publiceerbaar": "boolean"
    },
    numeric_fields: ["hoogteTovNap", "jaar", "xCoordinaatMuurvlak", "yCoordinaatMuurvlak", "statusCode"],
  },
  "meetbouten/meetbouten": {
    fields: {
    "identificatie": "string",
    "nabijNummeraanduiding": "string",
    "locatie": "string",
    "statusCode": "integer",
    "statusOmschrijving": "string",
    "vervaldatum": "date",
    "merkCode": "string",
    "merkOmschrijving": "string",
    "xCoordinaatMuurvlak": "integer",
    "yCoordinaatMuurvlak": "integer",
    "windrichting": "string",
    "ligtInBouwblokId": "string",
    "ligtInBuurtId": "string",
    "ligtInStadsdeelId": "string",
    "publiceerbaar": "boolean"
    },
    numeric_fields: ["statusCode", "xCoordinaatMuurvlak", "yCoordinaatMuurvlak"],
  },
  "civieleconstructies/kademuur": {
    fields: {
    "id": "string",
    "beheerder": "string",
    "beheerderGedetailleerd": "string",
    "beheergebied": "string",
    "eigenaar": "string",
    "fundering": "string",
    "materiaal": "string",
    "nenTypeBeheerobject": "string",
    "objectnummer": "string",
    "objectnaam": "unknown",
    "objecttype": "string",
    "beheerafspraak": "string",
    "type": "string"
    },
    numeric_fields: [],
  },
  "bouwstroompunten/bouwstroompunten": {
    fields: {
    "id": "string",
    "bouwstroompuntId": "string",
    "provincie": "string",
    "capaciteit": "string",
    "locatie": "string",
    "beschikbareAansluitingen": "array",
    "postcode": "string",
    "straat": "string",
    "huisnummer": "string",
    "plaats": "string",
    "vergunningsplichtig": "boolean",
    "contactPersoon": "unknown",
    "organisatie": "string",
    "gemeente": "string",
    "email": "string",
    "datumtijdAangemaakt": "unknown",
    "toegangswijze": "string",
    "primaireFunctie": "string",
    "minimaleGebruikscapaciteit": "string",
    "afbeelding": "unknown",
    "contactnummerBijMeldenStoring": "unknown",
    "teGebruikenApplicatie": "string",
    "nietBeschikbaarOp": "unknown",
    "aanmeldformulierAanvraagGebruik": "string"
    },
    numeric_fields: [],
  },
  "objectenopenbareruimte/afvalbakken": {
    fields: {
    "id": "string",
    "naam": "string",
    "actief": "string",
    "rdx": "string",
    "rdy": "string",
    "type": "string",
    "huisnummer": "string",
    "postcode": "string",
    "straatnaam": "string",
    "bouwjaar": "string",
    "levensduur": "string",
    "vervangjaar": "string",
    "objectgroep": "string",
    "vervangingsprijs": "string",
    "aanschafprijs": "string",
    "aantal": "string",
    "hoogte": "string",
    "lengte": "string",
    "breedte": "string",
    "vervangingsprijsTotaal": "string",
    "inhoud": "string",
    "beheerder": "string",
    "buurtId": "string",
    "buurtCode": "string",
    "buurtNaam": "string",
    "wijkCode": "string",
    "wijkNaam": "string",
    "ggwGebiedCode": "string",
    "ggwGebiedNaam": "string",
    "stadsdeelCode": "string",
    "stadsdeelNaam": "string",
    "gemeenteNaam": "unknown"
    },
    numeric_fields: [],
  },
  "bodem/grond": {
    fields: {
    "id": "integer",
    "locatie": "string",
    "amNummer": "string",
    "typeOnderzoek": "string",
    "rapportnummer": "string",
    "onderzoeksbureau": "string",
    "rapportdatum": "string",
    "naamBoring": "string",
    "xcoordinaat": "integer",
    "ycoordinaat": "integer",
    "grondwaterstand": "integer",
    "naamMonster": "string",
    "typeMonster": "string",
    "materiaal": "string",
    "bovenkant": "integer",
    "onderkant": "integer",
    "eindoordeel": "string",
    "waardeLutum": "integer",
    "waardeOrganischeStof": "integer",
    "waardeCadmium": "integer",
    "waardeKwik": "integer",
    "waardeKoper": "integer",
    "waardeNikkel": "integer",
    "waardeLood": "integer",
    "waardeZink": "integer",
    "waardeChroom": "integer",
    "waardeArseen": "integer",
    "waardePak": "integer",
    "waardeEox": "integer",
    "waardePcb": "integer",
    "waardeMineraleOlie": "integer"
    },
    numeric_fields: ["id", "xcoordinaat", "ycoordinaat", "grondwaterstand", "bovenkant", "onderkant", "waardeLutum", "waardeOrganischeStof", "waardeCadmium", "waardeKwik", "waardeKoper", "waardeNikkel", "waardeLood", "waardeZink", "waardeChroom", "waardeArseen", "waardePak", "waardeEox", "waardePcb", "waardeMineraleOlie"],
  },
  "historische_bodeminformatie/onderzoeken": {
    fields: {
    "id": "integer",
    "naamRapport": "string",
    "nummerRapport": "string",
    "datumRapport": "date",
    "opdrachtgever": "string",
    "opdrachtnemer": "string",
    "locatieOfAdres": "string",
    "typeOnderzoek": "string",
    "indicatieKwaliteit": "string",
    "beschrijving": "string",
    "permalink": "string"
    },
    numeric_fields: ["id"],
  },
  "explosieven/verdachtgebied": {
    fields: {
    "id": "integer",
    "kenmerk": "string",
    "detailType": "string",
    "subtype": "string",
    "kaliber": "string",
    "aantal": "string",
    "verschijning": "string",
    "oorlogshandeling": "string",
    "afbakening": "string",
    "horizontaal": "string",
    "cartografie": "string",
    "opmerkingen": "string",
    "pdf": "string"
    },
    numeric_fields: ["id"],
  },
  "ontplofbare_oorlogsresten/inslagen": {
    fields: {
    "id": "integer",
    "kenmerkGeometrie": "string",
    "kenmerkOorlogshandelingen": "string",
    "datumIncident": "unknown",
    "soortHandeling": "string",
    "bron": "string",
    "datumIntekening": "date",
    "intekening": "string",
    "cartografischeOnnauwkeurigheid": "string",
    "bovengrensDiepteliggingM": "unknown",
    "ondergrensDiepteliggingM": "unknown",
    "referentiepeil": "unknown",
    "typeOntsteker": "unknown",
    "trillingsgevoelig": "unknown",
    "hyperlink": "string",
    "bewerkingsdatumGeometrie": "unknown",
    "uuidGeometrie": "string",
    "opmerkingen": "string"
    },
    numeric_fields: ["id"],
  },
  "leidingeninfrastructuur/waternet_rioolleidingen": {
    fields: {
    "globalid": "string",
    "objectnummer": "integer",
    "status": "string",
    "jaarGelegd": "integer",
    "soort": "string",
    "typeLeiding": "string",
    "vorm": "string",
    "diameter": "integer",
    "breedte": "unknown",
    "hoogte": "unknown",
    "materiaal": "string",
    "bobBeginpunt": "number",
    "bobEindpunt": "number",
    "stelselType": "string",
    "funderingstype": "string",
    "toelichting": "unknown",
    "globalidBeginknoop": "string",
    "globalidEindknoop": "string",
    "leveringsdatum": "date"
    },
    numeric_fields: ["objectnummer", "jaarGelegd", "diameter", "bobBeginpunt", "bobEindpunt"],
  },
  "bbga/kerncijfers": {
    fields: {
    "id": "string",
    "jaar": "integer",
    "gebiedcode15": "string",
    "waarde": "integer",
    "indicatorDefinitieId": "string"
    },
    numeric_fields: ["jaar", "waarde"],
  },
  "indicatoren/buurt": {
    fields: {
    "id": "string",
    "indNaam": "string",
    "indWaarde": "integer",
    "indTeller": "integer",
    "indNoemer": "integer",
    "indNorm": "unknown",
    "indNormBron": "unknown",
    "indNormDefinitie": "unknown",
    "indPeildatumAfleiding": "date",
    "indDefinitie": "string",
    "indVariableType": "unknown",
    "indDatatype": "string",
    "indGrootheid": "string",
    "indEenheid": "string",
    "indFrequentieAfleiding": "string",
    "indBron": "string",
    "indDomeinNaam": "string",
    "indTempUur": "unknown",
    "indTempDag": "unknown",
    "indTempWeek": "integer",
    "indTempMaand": "integer",
    "indTempKwartaal": "integer",
    "indTempHalfjaar": "integer",
    "indTempJaar": "integer",
    "indTempLustrum": "integer",
    "indTempDecennium": "integer",
    "indDirectie": "unknown",
    "indAfdeling": "unknown",
    "indBeginPeriode": "date",
    "indEindPeriode": "date",
    "indDoelenboom": "unknown",
    "indDoelenboomActiviteit": "unknown",
    "gbdBuurtId": "string",
    "gbdBuurtVolgnummer": "unknown",
    "gbdBuurtNaam": "string",
    "gbdWijkId": "string",
    "gbdWijkNaam": "string",
    "gbdGgwId": "string",
    "gbdGgwNaam": "string",
    "gbdStadsdeelId": "string",
    "gbdStadsdeelNaam": "string",
    "bagWoonplaatsId": "string",
    "bagWoonplaatsNaam": "string"
    },
    numeric_fields: ["indWaarde", "indTeller", "indNoemer", "indTempWeek", "indTempMaand", "indTempKwartaal", "indTempHalfjaar", "indTempJaar", "indTempLustrum", "indTempDecennium"],
  },
  "woz/objecten": {
    fields: {
    "volgnummer": "integer",
    "registratiedatum": "unknown",
    "wozobjectnummer": "string",
    "gebruikCode": "integer",
    "gebruikOmschrijving": "string",
    "soortObjectCode": "integer",
    "soortObjectOmschrijving": "string",
    "beginGeldigheid": "date",
    "eindGeldigheid": "unknown"
    },
    numeric_fields: ["volgnummer", "gebruikCode", "soortObjectCode"],
  },
  "gemeentelijk_vastgoed/gebouwobjecten": {
    fields: {
    "objectId": "integer",
    "straatnaam": "string",
    "huisnummer": "integer",
    "huisletter": "unknown",
    "huisnummertoevoeging": "string",
    "huisnummeraanduiding": "unknown",
    "eigendom": "string",
    "bagPandIds": "array"
    },
    numeric_fields: ["objectId", "huisnummer"],
  },
  "nieuwbouwplannen/woningbouwplannen_openbaar": {
    fields: {
    "id": "integer",
    "projectnaamAfkorting": "string",
    "buurtCode": "string",
    "buurtNaam": "string",
    "wijkCode": "string",
    "wijkNaam": "string",
    "gebiedCode": "string",
    "gebiedNaam": "string",
    "stadsdeelCode": "string",
    "stadsdeelNaam": "string",
    "zelfbouw": "string",
    "socialeHuurCorporatie": "string",
    "plaberumPublicatie": "string",
    "startBouwGepland": "date",
    "startBouwGerealiseerd": "date",
    "socialeHuurZelfstPerm": "integer",
    "middeldureHuur": "integer",
    "betaalbareKoop": "integer",
    "vrijeSectorHuur": "integer",
    "vrijeSectorKoop": "integer",
    "vrijeSectorNb": "integer",
    "onbekend": "integer",
    "jongeren": "string",
    "studenten": "string",
    "shOnzelfstEnOfTijdelijk": "string",
    "onzelfstandig": "string",
    "tijdelijk": "string",
    "totaal": "integer",
    "totaalZelfstPerm": "integer",
    "peildatum": "date"
    },
    numeric_fields: ["id", "socialeHuurZelfstPerm", "middeldureHuur", "betaalbareKoop", "vrijeSectorHuur", "vrijeSectorKoop", "vrijeSectorNb", "onbekend", "totaal", "totaalZelfstPerm"],
  },
  "grex/projecten": {
    fields: {
    "id": "integer",
    "plannaam": "string",
    "startdatum": "date",
    "planstatus": "string",
    "oppervlakte": "number"
    },
    numeric_fields: ["id", "oppervlakte"],
  },
  "precariobelasting/terrassen": {
    fields: {
    "id": "integer",
    "categorie": "string",
    "jaar": "integer",
    "stadsdeel": "string",
    "gebied": "string",
    "tariefOverdektTerrasPerJaarPerM2": "string",
    "tariefOnoverdektTerrasPerZomerseizoenPerM2": "string",
    "tariefOnoverdektTerrasPerWinterseizoenPerM2": "string"
    },
    numeric_fields: ["id", "jaar"],
  },
  "risicozones/bedrijven": {
    fields: {
    "id": "integer",
    "naamBedrijf": "string",
    "adresBedrijf": "string",
    "typeBedrijf": "string",
    "categorieBevi": "string",
    "bevoegdgezag": "string",
    "stadsdeel": "string",
    "aantalBronnen": "integer",
    "opmerkingen": "string"
    },
    numeric_fields: ["id", "aantalBronnen"],
  },
  "geluidszones/industrie": {
    fields: {
    "id": "integer",
    "naam": "string",
    "thema": "string",
    "themaToelichting": "string",
    "themaWetOfRegelgeving": "string",
    "themaDatumLaatsteWijziging": "string"
    },
    numeric_fields: ["id"],
  },
  "overlastgebieden/algemeenoverlast": {
    fields: {
    "id": "integer",
    "type": "string",
    "typering": "string",
    "soort": "unknown",
    "url": "string",
    "oovNaam": "string",
    "oovCode": "string",
    "geldigheidPeriode": "string",
    "geldigheidSpecificatie": "string"
    },
    numeric_fields: ["id"],
  },
  "veiligeafstanden/veiligeafstanden": {
    fields: {
    "id": "integer",
    "type": "string",
    "locatie": "string",
    "thema": "string",
    "themaToelichting": "string",
    "themaWetOfRegelgeving": "string",
    "themaDatumLaatsteWijziging": "string"
    },
    numeric_fields: ["id"],
  },
  "schiphol/geluidzones": {
    fields: {
    "id": "integer",
    "type": "string",
    "thema": "string",
    "themaToelichting": "string",
    "themaWetOfRegelgeving": "string",
    "themaDatumLaatsteWijziging": "string"
    },
    numeric_fields: ["id"],
  },
  "parkeervakken/parkeervakken": {
    fields: {
    "id": "string",
    "buurtcode": "string",
    "straatnaam": "string",
    "type": "string",
    "soort": "string",
    "eType": "unknown",
    "aantal": "integer",
    "versiedatum": "date",
    "regimes": "array"
    },
    numeric_fields: ["aantal"],
  },
  "parkeerzones/parkeerzones": {
    fields: {
    "id": "integer",
    "beginGeldigheid": "date",
    "eindGeldigheid": "unknown",
    "gebiedscode": "string",
    "gebiedsomschrijving": "string",
    "gebiedsnaam": "string",
    "gebiedsouder": "string",
    "domeincode": "string",
    "gebruiksdoel": "string",
    "indicatieZichtbaar": "string",
    "gebiedskleurcode": "string"
    },
    numeric_fields: ["id"],
  },
  "milieuzones/vrachtauto": {
    fields: {
    "id": "integer",
    "verkeerstype": "string",
    "vanafdatum": "string"
    },
    numeric_fields: ["id"],
  },
  "milieuzones2025/vracht_en_bestelauto": {
    fields: {
    "id": "integer"
    },
    numeric_fields: ["id"],
  },
  "uitstootvrije_zones/brom_en_snorfiets": {
    fields: {
    "id": "integer"
    },
    numeric_fields: ["id"],
  },
  "wegenbestand/routes_gevaarlijke_stoffen": {
    fields: {
    "id": "integer",
    "title": "string",
    "type": "string"
    },
    numeric_fields: ["id"],
  },
  "touringcars/haltes": {
    fields: {
    "id": "integer",
    "omschrijving": "string",
    "bijzonderheden": "string",
    "plaatsen": "string"
    },
    numeric_fields: ["id"],
  },
  "fietspaaltjes/fietspaaltjes": {
    fields: {
    "id": "string",
    "street": "string",
    "at": "string",
    "area": "string",
    "score2013": "unknown",
    "scoreCurrent": "string",
    "count": "integer",
    "paaltjesWeg": "array",
    "soortPaaltje": "array",
    "uiterlijk": "array",
    "type": "array",
    "ruimte": "array",
    "markering": "array",
    "beschadigingen": "array",
    "veiligheid": "array",
    "zichtInDonker": "array",
    "soortWeg": "array",
    "noodzaak": "array"
    },
    numeric_fields: ["count"],
  },
  "hoofdroutes/u_routes": {
    fields: {
    "id": "string",
    "name": "string",
    "route": "string",
    "type": "string"
    },
    numeric_fields: [],
  },
  "loopfietsnetwerk/edges": {
    fields: {
    "id": "integer",
    "wegklasse": "string",
    "hoogteniveau": "integer",
    "straatnaam": "string",
    "indicatieVoetFiets": "boolean",
    "indicatieBrug": "boolean",
    "indicatieTunnel": "boolean",
    "indicatieOvBus": "unknown",
    "indicatieSpoor": "unknown",
    "indicatieToegankelijkheid": "boolean",
    "typeVeerRoute": "unknown",
    "minimumBreedte": "number",
    "maximumBreedte": "number",
    "gewogenGemiddeldeBreedte": "number",
    "weight": "number",
    "maximumSnelheid": "integer",
    "startNodeId": "integer",
    "endNodeId": "integer",
    "datumExtractie": "date"
    },
    numeric_fields: ["id", "hoogteniveau", "minimumBreedte", "maximumBreedte", "gewogenGemiddeldeBreedte", "weight", "maximumSnelheid", "startNodeId", "endNodeId"],
  },
  "verkeersinformatiesystemen/verkeersinformatiesystemen": {
    fields: {
    "id": "string",
    "objectSoort": "string",
    "objecttypeVisKaart": "string",
    "beheerderGedetailleerd": "string",
    "jaarVanAanleg": "integer",
    "memo": "string",
    "model": "string",
    "objectnummer": "string",
    "objectnummerLeverancier": "string",
    "standplaats": "string",
    "type": "string",
    "typeGedetailleerd": "string"
    },
    numeric_fields: ["jaarVanAanleg"],
  },
  "gebieden/stadsdelen": {
    fields: {
    "identificatie": "string",
    "volgnummer": "integer",
    "registratiedatum": "date",
    "naam": "string",
    "code": "string",
    "beginGeldigheid": "date",
    "eindGeldigheid": "unknown",
    "documentdatum": "date",
    "documentnummer": "string",
    "ligtInGemeenteId": "string"
    },
    numeric_fields: ["volgnummer"],
  },
  "gebieden/wijken": {
    fields: {
    "identificatie": "string",
    "volgnummer": "integer",
    "registratiedatum": "date",
    "naam": "string",
    "code": "string",
    "beginGeldigheid": "date",
    "eindGeldigheid": "unknown",
    "documentdatum": "date",
    "documentnummer": "string",
    "cbsCode": "string",
    "ligtInStadsdeelId": "string",
    "ligtInGgwgebiedId": "string"
    },
    numeric_fields: ["volgnummer"],
  },
  "gebieden/buurten": {
    fields: {
    "volgnummer": "integer",
    "registratiedatum": "date",
    "identificatie": "string",
    "naam": "string",
    "code": "string",
    "beginGeldigheid": "date",
    "eindGeldigheid": "unknown",
    "documentdatum": "date",
    "documentnummer": "string",
    "cbsCode": "string",
    "ligtInWijkId": "string",
    "ligtInGgpgebiedId": "unknown",
    "ligtInGgwgebiedId": "string"
    },
    numeric_fields: ["volgnummer"],
  },
  "gebieden/ggwgebieden": {
    fields: {
    "identificatie": "string",
    "volgnummer": "integer",
    "registratiedatum": "date",
    "naam": "string",
    "code": "string",
    "beginGeldigheid": "date",
    "eindGeldigheid": "unknown",
    "documentdatum": "date",
    "documentnummer": "string",
    "ligtInStadsdeelId": "string"
    },
    numeric_fields: ["volgnummer"],
  },
  "gebieden/grootstedelijke_projecten": {
    fields: {
    "id": "integer",
    "naam": "string",
    "type": "string",
    "url": "string",
    "typering": "string",
    "datum": "string",
    "legenda": "string"
    },
    numeric_fields: ["id"],
  },
  "water/binnenwater": {
    fields: {
    "id": "integer"
    },
    numeric_fields: ["id"],
  },
  "varen/ligplaats": {
    fields: {
    "id": "string",
    "naamVaartuig": "string",
    "naamKlantKvk": "string",
    "ligplaatsSegment": "string",
    "kenmerkVergunning": "string",
    "datumEindeVergunning": "string",
    "idLigplaats": "string",
    "verwerkingsdatum": "date",
    "gbdBuurtId": "unknown",
    "locatieAdres": "string"
    },
    numeric_fields: [],
  },
  "wior/wior": {
    fields: {
    "id": "string",
    "wiorNummer": "string",
    "projectnaam": "string",
    "beschrijving": "string",
    "datumStartUitvoering": "date",
    "datumEindeUitvoering": "date",
    "periodeGeplandeUitvoering": "string",
    "hoofdstatus": "string",
    "typeWerkzaamheden": "string"
    },
    numeric_fields: [],
  },
  "storingsmeldingen_ovl_en_klokken/openbare_verlichting": {
    fields: {
    "objectId": "integer",
    "objecttype": "string",
    "objecttypeOmschrijving": "string",
    "objectnummer": "string",
    "breedtegraad": "number",
    "lengtegraad": "number",
    "storingstatus": "integer",
    "meldingstatus": "integer"
    },
    numeric_fields: ["objectId", "breedtegraad", "lengtegraad", "storingstatus", "meldingstatus"],
  },
  "stroomstoringen/stroomstoringen": {
    fields: {
    "id": "integer",
    "storingNummer": "integer",
    "storingGetroffenPostcodes": "string",
    "storingType": "string",
    "storingEnergiesoort": "string",
    "storingStatus": "string",
    "storingDatumGemeld": "date",
    "storingDatumSchatting": "date",
    "storingDatumEind": "date",
    "storingComponent": "string",
    "storingOorzaak": "string",
    "storingGetroffenKlanten": "string",
    "storingGetroffenStraten": "string",
    "storingDatumWijziging": "date",
    "storingServiceUpdate": "date",
    "mutatieActie": "string",
    "datumEind": "date",
    "storingGetroffenPlaatsen": "string",
    "datumLog": "date",
    "gestoordGebied": "string",
    "gestoordGebiedLengte": "string"
    },
    numeric_fields: ["id", "storingNummer"],
  },
  "verkiezingen/processenverbaal": {
    fields: {
    "id": "integer",
    "verkiezingsjaar": "integer",
    "documentnaam": "string",
    "volgnummer": "integer",
    "uri": "string"
    },
    numeric_fields: ["id", "verkiezingsjaar", "volgnummer"],
  },
  "sport/openbaresportplek": {
    fields: {
    "id": "integer",
    "naam": "string",
    "sportvoorziening": "string",
    "soortLocatie": "string",
    "soortOmheining": "string",
    "soortOndergrond": "string",
    "soortVerlichting": "string",
    "indicatieOverdekt": "string",
    "omschrijving": "string",
    "oppervlakte": "integer",
    "foto": "string"
    },
    numeric_fields: ["id", "oppervlakte"],
  },
  "maatschappelijke_voorzieningen/voorziening_individueel": {
    fields: {
    "id": "string",
    "mvId": "string",
    "naam": "string",
    "status": "string",
    "ingepast": "string",
    "typeGebouw": "string",
    "zaaldelen": "unknown",
    "functionaliteit": "string",
    "bezetting": "string",
    "verwarmingsinstallatie": "unknown",
    "actiefVanaf": "date",
    "actiefTot": "unknown",
    "changedDate": "date",
    "createdDate": "date",
    "voorzieningIndividueelVoorzieningGeneriek": "string",
    "voorzieningIndividueelGebouw": "string",
    "voorzieningIndividueelDomein": "string",
    "voorzieningIndividueelEigendom": "string",
    "voorzieningIndividueelCategorie": "string",
    "voorzieningIndividueelTypeVoorziening": "string",
    "voorzieningIndividueelAdres": "string"
    },
    numeric_fields: [],
  },
  "schoolgebouwen/accommodatie": {
    fields: {
    "id": "string",
    "accommodatieId": "string",
    "instellingId": "string",
    "code": "string",
    "adresStraat": "string",
    "adresPostcode": "string",
    "adresHuisnummer": "string",
    "adresHuisnummerToev": "unknown",
    "stadsdeel": "string",
    "wijk": "string",
    "bestemming": "string",
    "bvo": "string",
    "onderwijs": "string",
    "bouwaard": "string",
    "bouwjaar": "string",
    "renovatieDatum": "unknown",
    "bouwlagen": "string",
    "schoolpleinM2": "string",
    "speellokalen": "string",
    "juridischEigenaar": "string",
    "economischClaimrecht": "string",
    "archief": "string",
    "archiefDatum": "string",
    "datumExport": "string",
    "versie": "string",
    "mGeldigVan": "date",
    "mGeldigTot": "date",
    "mIsActief": "boolean"
    },
    numeric_fields: [],
  },
  "primair_onderwijs_loopafstanden/afstanden": {
    fields: {
    "routeId": "string",
    "peildatumNetwerk": "date",
    "peildatumAdressen": "date",
    "bkAdres": "string",
    "straatnaam": "unknown",
    "huisnummer": "unknown",
    "huisletter": "unknown",
    "huisnummertoevoeging": "unknown",
    "postcode": "unknown",
    "woonplaats": "unknown",
    "gemeente": "unknown",
    "lonAdres": "number",
    "latAdres": "number",
    "buniek": "string",
    "bkSchool": "string",
    "lonSchool": "number",
    "latSchool": "number",
    "afstand": "integer",
    "rang": "integer"
    },
    numeric_fields: ["lonAdres", "latAdres", "lonSchool", "latSchool", "afstand", "rang"],
  },
  "winkelgebieden/winkelgebieden": {
    fields: {
    "id": "integer",
    "gebiedscode": "unknown",
    "gebiedsnaam": "string",
    "code": "unknown",
    "oppervlakte": "number",
    "winkelgebiedcode": "string",
    "concentratiegebiedcode": "unknown",
    "concentratiegebiednaam": "unknown",
    "wijk": "string",
    "gebied": "string",
    "categorie": "string",
    "categorienaam": "string"
    },
    numeric_fields: ["id", "oppervlakte"],
  },
  "vergunningen/omzetting": {
    fields: {
    "id": "integer",
    "wijkNaam": "string",
    "categorieKleur": "string"
    },
    numeric_fields: ["id"],
  },
  "evenementen/evenementen": {
    fields: {
    "id": "integer",
    "titel": "string",
    "omschrijving": "string",
    "startdatum": "date",
    "einddatum": "date",
    "starttijd": "unknown",
    "eindtijd": "unknown",
    "url": "string"
    },
    numeric_fields: ["id"],
  },
  "horeca/exploitatievergunning": {
    fields: {
    "id": "integer",
    "zaaknummer": "integer",
    "zaaknaam": "string",
    "adres": "string",
    "zaakCategorie": "string",
    "zaakSpecificatie": "string",
    "begindatum": "date",
    "einddatum": "date",
    "openingstijdenZoDoVan": "string",
    "openingstijdenZoDoTot": "string",
    "openingstijdenVrZaVan": "string",
    "openingstijdenVrZaTot": "string",
    "oTijdenTerrasZoDoVan": "string",
    "oTijdenTerrasZoDoTot": "string",
    "oTijdenTerrasVrZaVan": "string",
    "oTijdenTerrasVrZaTot": "string",
    "postcode": "string",
    "statusVergunning": "string",
    "statusTijdelijkTerras": "unknown",
    "toestemmingTijdelijkTerras": "unknown",
    "publBesluitTijdelijkTerras": "unknown",
    "tijdelijkTerrasDetails": "unknown",
    "statusVerlengingTijdelijkTerras": "unknown",
    "verlengingTijdelijkTerrasDetails": "unknown",
    "terrasgeometrie": "unknown"
    },
    numeric_fields: ["id", "zaaknummer"],
  },
  "bedrijveninvesteringszones/gebieden": {
    fields: {
    "id": "integer",
    "naam": "string",
    "type": "string",
    "heffingsgrondslag": "string",
    "aantalBijdrageplichtigen": "integer",
    "heffingstarief": "integer",
    "verordening": "string",
    "urlVerordening": "string"
    },
    numeric_fields: ["id", "aantalBijdrageplichtigen", "heffingstarief"],
  },
};
